FROM pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime

WORKDIR /app

COPY ./requirements.txt .
COPY ./src/train.py ./train.py
COPY ./src/data ./data
COPY ./src/models ./models
COPY ./docker/start-train.sh ./start-train.sh

RUN mkdir -p /app/logs /app/results

RUN pip3 install -r requirements.txt

RUN chmod +x start-train.sh

ENV MODEL_OUTPUT_DIR=/app/results

CMD ["bash", "./start-train.sh"]
