FROM pytorch/pytorch:2.2.2-cuda11.8-cudnn8-runtime

WORKDIR /app

COPY ./src/serving ./serving
COPY ./src/results ./results
COPY ./docker/start-serve.sh ./start.sh
COPY ./src/models/config.py ./models/config.py
COPY ./requirements.txt .

RUN pip3 install -r requirements.txt

RUN chmod +x start-serve.sh

CMD ["bash", "./start-serve.sh"]

